---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world
spec:
  params:
    - name: greet
      default: "Hello from Pipeline"
  workspaces:
    - name: git-source
  tasks:
    - name: echo-hello-world
      taskRef:
        name: echo-hello-world
      params:
        - name: greet
          value: $(params.greet)
      # workspaces:
      # - name: git-source
