---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: dockerhub-sugardonblog-update-helm-tag
spec:
  triggers:
    - name: dockerhub
      interceptors:
        - cel:
            filter: "body.repository.repo_name in ['sugardon/sugardonblog']"
        - cel:
            filter: "!body.push_data.tag.endsWith('.sig')"
      bindings:
        - ref: dockerhub
      template:
        ref: update-helm-tag
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-triggers-example-sa
