---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tekton-cicd
resources:
  - ingress.yaml
  - github-sugardon-nextjs-typescript-tutorials.yaml
  - dockerhub-sugardonblog-update-helm-tag.yaml
