---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-ci
  namespace: helmfile-argocd-default
spec:
  project: default
  source:
    directory:
      recurse: false
    path: tests/overlays/development
    repoURL: https://github.com/sugardon-org/tekton-ci
    targetRevision: HEAD
  destination:
    namespace: tekton-ci
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
