---
oauth2-proxy:
  extraArgs:
  # https://github.com/oauth2-proxy/oauth2-proxy/blob/master/docs/docs/configuration/overview.md
    provider: github
    github-org: sugardon-org
    github-team: admin
    set-authorization-header: true
    upstream: "http://tekton-dashboard:9097"
  config:
    existingSecret: dashboard-oauth2proxy
  redis:
    enabled: false
