---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-hello-world
spec:
  params:
    - name: greet
      type: string
      description: The string comment for greeting
      default: Have a nice day! (DEFAULT)
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "Hello World $(params.greet)"
