---
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  profile: all
  pruner:
    resources:
      - taskrun
      - pipelinerun
    keep: 6
    schedule: "0 0 * * *"

---
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonChain
metadata:
  name: chain
spec:
  targetNamespace: tekton-cicd
