---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tekton-cicd
resources:
  # shipwright
  # https://github.com/shipwright-io
  - https://github.com/shipwright-io/build/releases/download/v0.10.0/release.yaml
  - https://github.com/shipwright-io/build/releases/download/v0.10.0/sample-strategies.yaml
