---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-world
spec:
  params:
    - name: greet
      value: "Hello from PipelineRun"
  pipelineRef:
    name: hello-world
  serviceAccountName: dockerhub-account
  workspaces:
    - name: git-source
      volumeClaimTemplate:
        # https://github.com/tektoncd/pipeline/blob/main/docs/workspaces.md#volumeclaimtemplate
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
          storageClassName: tekton-dev-sc
          requests:
            storage: 1Gi
